#lang scheme
(define (f n)
  (define a (quotient n 10))
  (define b (remainder n 10))
  (if (or (< n 20) (= n 100) ) 
  (cond ((= n 1) (display "один"))
        ((= n 2) (display "два"))
        ((= n 3) (display "три"))
        ((= n 4) (display "четыре"))
        ((= n 5) (display "пять"))
        ((= n 6) (display "шесть"))
        ((= n 7) (display "семь"))
        ((= n 8) (display "восемь"))
        ((= n 9) (display "девять"))
        ((= n 10) (display "десять"))
        ((= n 11) (display "одиннадцать"))
        ((= n 12) (display "двенадцать"))
        ((= n 13) (display "тринадцать"))
        ((= n 14) (display "четырнадцать"))
        ((= n 15) (display "пятнадцать"))
        ((= n 16) (display "шестнадцать"))
        ((= n 17) (display "семнадцать"))
        ((= n 18) (display "восемьнадцать"))
        ((= n 19) (display "девятнадцать"))
        ((= n 100) (display "сто")) )
  (and (cond
        ((= a 2) (display "двадцать"))
        ((= a 3) (display "тридцать"))
        ((= a 4) (display "сорок"))
        ((= a 5) (display "пятьдесят"))
        ((= a 6) (display "шестьдесят"))
        ((= a 7) (display "семьдесят"))
        ((= a 8) (display "восемьдесят"))
        ((= a 9) (display "девяносто")) )
        (cond
        ((= b 1) (display " один"))
        ((= b 2) (display " два"))
        ((= b 3) (display " три"))
        ((= b 4) (display " четыре"))
        ((= b 5) (display " пять"))
        ((= b 6) (display " шесть"))
        ((= b 7) (display " семь"))
        ((= b 8) (display " восемь"))
        ((= b 9) (display " девять")) ) ) ) )
